services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  caddy:
    image: caddy:2.10-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      # port 80 for redirection
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/logs:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - web

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: