services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEB_PORT=${WEB_PORT}
    networks:
      - app-network
    env_file: "web.env"

  caddy:
    image: caddy:2.10-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      # port 80 for redirection
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/logs:/var/log/caddy
      - ./caddy/certs:/etc/caddy/certs:ro  # Mount certificates directory
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - web
    env_file: "web.env"

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: